version: "3"
services:
    app:
      build: .
      command: ["node", "src/app.js"]
      environment:
        - SECOND_SERVICE_URL=http://app2:3001
      ports:
        - 80:3000
      volumes:
        - ./logs:/usr/src/app/logs
        - ./static:/usr/src/app/static

    app2:
      build: .
      command: ["node", "src/app2.js"]
      ports:
       - 3001:3001
      volumes:
       - ~/.aws/:/root/.aws:ro
      